### ISSUE TITLE
µBlock -> uBlock

### ISSUE THREAD

**Issue by mikhaelkh** [uBlock-LLC/uBlock#1070]
In options, in up-left corner is still µBlock in some localizations, for example, Russian.

**Comment by gorhill** [comment]
Fixed with db301e9f647ab69584d55618be198dc55bd424ac.

**Comment by alejandrolemus** [comment]
More µBlock?? Firefox 36.0.4, version 0.9.2.1-dev1

![ublock](https://cloud.githubusercontent.com/assets/9505902/6769797/419bd9cc-d07f-11e4-9d65-14fc204df829.png)

**Comment by alejandrolemus** [comment]
@gorhill  Weird, somehow I still see the previous issue with 0.9.2.1-rc.0, even after restarting Firefox. Is [this change](https://github.com/gorhill/uBlock/commit/e642423a550994e8ab5eb0f7b57f4d14909a46b0) included in this version, right?

**Comment by gorhill** [comment]
The names are refreshed once you force a change in the filter lists, for example, un-check cosmetic filtering, apply, check it back, apply.

**Comment by alejandrolemus** [comment]
Yes, perfect now! Thanks

**Comment by josteink** [comment]
One small step for man, one giant leap for illiteracy ;)

**Comment by tjharman** [comment]
This makes me sad! Long live µBlock!

**Comment by akaleeroy** [comment]
Will still call it µBlock because uBlock sounds like adware from the 90s. Or a part of a prison.

**Comment by iandol** [comment]
> One small step for man, one giant leap for illiteracy ;)

Ha, indeed! So sad the unwashed masses know nothing about a character that is essential for both science and the classics!

**Comment by GXTX** [comment]
@gorhill What a waste... everybody knows it's pronounced microblock.

**Comment by mikhaelkh** [comment]
µBlock is still there... It's in the name of Russian dashboard tab.

**Comment by gorhill** [comment]
This needs to be fixed on Crowdin.
