### ISSUE TITLE
CNN video not working

### ISSUE THREAD

**Issue by elad** [uBlock-LLC/uBlock#1240]
Hello,

Earlier today I decided to give uBlock a try instead of AdBlock (Chrome, Mac OS X Yosemite). Just came across a potential bug: video on CNN doesn't work.

For example, [this video](http://www.cnn.com/videos/tv/2015/04/10/erin-hancocks-kim-jong-un-condition.cnn) of Kim Jong Un in an amusement park doesn't play. With AdBlock it does, properly skipping to the video and not showing the ad.

**Comment by chrisaljoudi** [comment]
Hi @elad!

Thanks for giving uBlock a try. uBlock comes with more filter lists enabled out of the box than AdBlock or ABP (to protect your privacy).

I've just pushed the fix for this in e097d20. All you have to do now is simply update uBlock's filter lists from the preferences:

![screen shot 2015-04-11 at 6 30 37 pm](https://cloud.githubusercontent.com/assets/2351359/7103882/e1c95e2a-e078-11e4-9603-443c40e6f442.png)

Thanks, and please enjoy uBlock.

**Comment by elad** [comment]
Confirmed fixed! Fantastic response time, you just earned a new user & advocate. :) Thanks!

**Comment by yanksno1** [comment]
I'm also having this issue. I tried updating my 3rd-party filters (hit Purge all caches, then the Update now buttons) and it's still not working. Is there anything else I should try?

**Comment by Snapy** [comment]
@yanksno1 Add the filter manually in the "My filters" tab.

**Comment by yanksno1** [comment]
Thanks for pointing me in the right direction, adding it manually worked.
