### ISSUE TITLE
Disappearing Gmail Labels

### ISSUE THREAD

**Issue by mbadolato** [uBlock-LLC/uBlock#456]
Earlier this week I noticed that 4 of the labels in Gmail were blank. They showed no text, however they were empty placeholders (and the blank space could still be clicked on and take me into that label/folder). 

The four were my labels for Facebook, LinkedIn, Twitter, and Google+.  If I went into label management and renamed them, they would show up (say Facebook -> Facebook1). But then renaming them back caused them to blank out again.

![missing_labels](https://cloud.githubusercontent.com/assets/164615/5593385/2f3258ac-91c7-11e4-8daf-0aed8ec1fcb6.png)

I decided to check out settings in uBlock since I had just switched to it from AdBlocker Plus right around the time that I noticed the issue. When I tried disabling the Fanboy's Social Blocking List plugin, I discovered that was the cause. With it disabled, the labels showed up again. 

Not sure if this is a uBlock issue or a Fanboy's Social Blocking issue, but figured I'd let you know.

**Comment by gorhill** [comment]
I see exception filters in _"Fanboy's Social Block List"_:

```
mail.google.com#@#a[title="Facebook"]
mail.google.com#@#a[title="Google Plus"]
mail.google.com#@#a[title="Google+"]
mail.google.com#@#a[title="LinkedIn"]
mail.google.com#@#a[title="Pinterest"]
mail.google.com#@#a[title="Twitter"]
mail.google.com#@#a[title="Youtube"]
```

So the issue is probably related to issue #452, which is fixed in version 0.8.2.4 (which I posted minutes ago to the Chrome store). Looks like the issue may have affected more users than I thought.

If you can confirm it is fixed once you get 0.8.2.4.

**Comment by mbadolato** [comment]
@gorhill Thanks for the quick reply

Not fixed. I installed 0.8.2.4 (confirmed on my extension screen), re-enabled the plugin, and the labels blanked out again. I did try quitting and restarting Chrome, just in case uBlock needed it.

**Comment by gorhill** [comment]
Not a Gmail user here, but I have an account for testing purpose. Where are these labels?

**Comment by gorhill** [comment]
Never mind, I see it -- or rather, I can see it's not visible.

**Comment by mbadolato** [comment]
Settings->Labels and create them. They'll appear on your left-hand side where Inbox, Drafts etc are

**Comment by mbadolato** [comment]
Hah github comment/reply race condition :smile:

**Comment by gorhill** [comment]
Ok I see the problem, will fix.

**Comment by mbadolato** [comment]
Great! I'll test it as soon as the new version hits the Chrome store.

**Comment by gorhill** [comment]
Just posted to Chrome store, should be there after 60 minutes.

**Comment by mbadolato** [comment]
OK, I'll check back in a bit

**Comment by mbadolato** [comment]
Confirmed working for me now. Thanks much for the speedy fix and for creating a great extension. Cheers!

**Comment by mbadolato** [comment]
@gorhill I spoke to soon. I just quit Chrome, reopened, and the labels are gone again :frowning:

**Comment by mbadolato** [comment]
Interesting. If I disable the plugin and refresh Gmail, I see the labels. If I then enable it and refresh it's still ok. But if I then quit and reopen chrome, the labels are gone. 

If the plugin is enabled and the labels don't show (after the quit and restart), and I disable the plugin and refresh, the labels come back.

**Comment by gorhill** [comment]
Could you force an update of your filter lists? (Purge all caches)

**Comment by gorhill** [comment]
Never mind I see it. There is something else happening then. At launch, the content scripts are injected manually, so it seems this is where there is a problem.

**Comment by gorhill** [comment]
Yes, it's related to injecting the content scripts manually, different problem than the one solved above.

Since fix to #426, maybe not injecting the content scripts manually is now an option...

**Comment by mbadolato** [comment]
Looks like that did it!

**Comment by Jestar342** [comment]
This exception is being raised even if uBlock is turned off. 

edit: I'll create a new issue

**Comment by Gitoffthelawn** [comment]
@Jestar342 Not sure if by "turned off" you mean "disabled" or "turned off for the site".

If the issue can be reproduced with uBlock turned off for the site, try momentarily disabling the uBlock extension completely.  If it's still an issue, you will want to tell the company that produces your webmail (Google) about their issue.

If you will, let us know if the issue persists even with uBlock temporarily disabled.

**Comment by Jestar342** [comment]
Hi, thanks for the reply. I've created a new issue (#1641) with further details.

**Comment by chrcoluk** [comment]
I have a page that loads blank, I ran it through developer tools in chrome, and it showed a url that points to here from ublock debug information.

The url is https://www.owasp.org/index.php/PHP_Configuration_Cheat_Sheet

Here is lines of code

> // Abort execution by throwing if an unexpected condition arise.
// - https://github.com/chrisaljoudi/uBlock/issues/456

**Comment by ghost** [comment]
Happens in uBlock Origin 1.11.5.108 **EDIT:** and  1.12.3.0
when loading an image url like this:
https://cloud.githubusercontent.com/assets/26243389/23693468/ebc4e79c-03d4-11e7-84d1-ecd56b9147a0.png
you see in `Errors`:
`Uncaught Error: uBlock Origin: aborting content scripts for https://cloud.githubusercontent.com/assets/26243389/23693468/ebc4e79c-03d4-11e7-84d1-ecd56b9147a0.png`

actual line:
```javascript
// Abort execution by throwing if an unexpected condition arise.
// - https://github.com/chrisaljoudi/uBlock/issues/456

if ( typeof vAPI !== 'object' ) {
    throw new Error('uBlock Origin: aborting content scripts for ' + window.location);
}
```

**Comment by Gitoffthelawn** [comment]
@xftroxgpx You may want to report that in the uBlock Origin repo on GitHub.

**Comment by ghost** [comment]
Thanks. Looks like I posted in the wrong issue here too. Whoops!
**EDIT:** Oh wait, nevermind: I posted here because there's a link to this in uBO source code. I now added those in my previous comment.
Anyway, doesn't matter. I just wanted to add another case to repro the issue.
