### ISSUE TITLE
"Resource interpreted as Font but transferred with MIME type text/html"

### ISSUE THREAD

**Issue by ArnaudLigny** [uBlock-LLC/uBlock#457]
Returned by the Google Chrome console on "https://gamesdonequick.com" with default settings.

uBlock enabled:
![games done quick - ko](https://cloud.githubusercontent.com/assets/80580/5593654/108ae656-921e-11e4-9423-bcf29c87ddd1.png)

uBlock disabled:
![games done quick - ok](https://cloud.githubusercontent.com/assets/80580/5593655/108c33e4-921e-11e4-956b-75858ab84262.png)

**Comment by gorhill** [comment]
Dup of #291?

**Comment by ArnaudLigny** [comment]
Yep, and more: I just updated uBlock to the 0.8.2.4 release and it seems the problem is fixed! :-)

**Comment by gorhill** [comment]
No, not fixed. It's just that when uBlock updates, it flushed cached data to be sure the latest one shipped with the extension is used. Refresh the page to let the content locally mirrored, and the bug will come back.

**Comment by gorhill** [comment]
Actually, I am going to exclude `maxcdn.bootstrapcdn.com/font-awesome/*.css` as a candidate for mirroring, it just does not work with `data:` URI.

**Comment by ArnaudLigny** [comment]
> Refresh the page to let the content locally mirrored, and the bug will come back.

Crap, you are right. I am sorry for the loss of time.
