### ISSUE TITLE
Blocking different kind of pop-ups

### ISSUE THREAD

**Issue by Deathamns** [uBlock-LLC/uBlock#510]
[Here](http://raymondhill.net/ublock/popup.html) is the test case I used for Firefox.
Chrome only blocks the first three types.

**Comment by gorhill** [comment]
I could host the server-side code on my server. Very useful, instead of going around to try to find some test cases.

**Comment by Deathamns** [comment]
1. Allow CORS for XHR.
2. t.php: `<?php header('Location: t1.php');`
3. t1.php: `<?php header('Location: http://example.com/AdHandler.aspx?');`

Save the HTML, change the URLs which are pointing to the php files, upload.

**Comment by gorhill** [comment]
http://raymondhill.net/ublock/popup.html

**Comment by Deathamns** [comment]
data:uri link redirect should have a full URL, and the XHR URL too.

**Comment by gorhill** [comment]
Fixed now?

**Comment by Deathamns** [comment]
:63 `http://raymondhill.net/ublock/popup-t.php` instead of `popup-t.php`
:72 `http://raymondhill.net/ublock/AdHandler.aspx?` instead of `?AdHandler.aspx?`
(since the baseURI is not inherited...)

**Comment by gorhill** [comment]
Yes, that's what I fixed. Oh wait.. 72 is wrong.... Fixed

**Comment by Deathamns** [comment]
Have you uploaded it too? Because I still don't see the full URLs.

**Comment by gorhill** [comment]
Now I did, I was uploading at the wrong location..

**Comment by Deathamns** [comment]
Seems okay, except 11. Chrome should display "not ok" (for now). Maybe upload an empty `AdHandler.aspx` too.

**Comment by Deathamns** [comment]
A few of the examples above could be easily supported in Chrome, by allowing `about:blank` and `data:` type URIs for the main frame. So, basically allow a pagestore to be created for these URLs.
In Firefox, I just [faked](https://github.com/gorhill/uBlock/blob/master/platform/firefox/vapi-background.js#L1090) http URLs for them, but that is not a solution.

Because of this, I simply ignored `vAPI.tabs.onNavigation` for non-http pages (because in that step the pagestore is destroyed, meaning no ads will be blocked in the pop-up), which is now causing #522.

**Comment by gorhill** [comment]
> allowing about:blank and data: type URIs for the main frame

Yes, I will go the uMatrix route: allow uBlock on these, as I want uBlock to now catch everything since it can disclose all connections. This will also take care of issue #105.

**Comment by gorhill** [comment]
@Deathamns:

> A few of the examples above could be easily supported in Chrome, by allowing about:blank and data: type URIs for the main frame. So, basically allow a pagestore to be created for these URLs.
> In Firefox, I just faked http URLs for them, but that is not a solution.

This is fixed in branch https://github.com/gorhill/uBlock/tree/fix-475. However I am not sure if Firefox code needs more changes than what I did. Also, is there such a thing as "behind-the-scene" in Firefox?

If so, they should be reported with the tab id set to `vAPI.noTabId`.

**Comment by Deathamns** [comment]
> if Firefox code needs more changes

Probably [frameModule.js](https://github.com/gorhill/uBlock/blob/master/platform/firefox/frameModule.js#L122) needs to be changed.

> If so, they should be reported with the tab id set to  `vAPI.noTabId`.

It returns -1 (just like others) for requests that are not related to tabs [:370](https://github.com/gorhill/uBlock/blob/master/platform/firefox/vapi-background.js#L370).

**Comment by Deathamns** [comment]
[URL](http://www.promptfile.com/l/80F6C049CB-7E5CB374A5); pop-up (via clicking) not blocked.
No problem in similar extensions (Chrome too).

**Comment by gorhill** [comment]
Isn't just a filter thing? If I use `||racksauce.com^` (or block dynamically) no popup.

**Edit:** I see a regular expression filter in EasyList for `promptfile.com`:

```
/^https?\:\/\/(?!(connect\.facebook\.net|www\.google-analytics\.com|ajax\.googleapis\.com|netdna\.bootstrapcdn\.com|[\w\-]+\.addthis\.com|bp\.yahooapis\.com|b\.scorecardresearch\.com|platform\.twitter\.com)\/)/$script,third-party,xmlhttprequest,domain=promptfile.com
```

I don't want uBlock to support regex if there are other ways to do the same thing. Which is the case here: **only** `||racksauce.com^` is needed along with the default selection of lists instead of that large regular expression.

**Comment by Deathamns** [comment]
I didn't check. It didn't seem right, so I made a note for later testing.
But, yes, it seems that it is blocked in ABP because of a regular expression type filter.

**Comment by ryanbr** [comment]
regex was only supported because the domains were changing so often, it was easier to block via regex. Does uBlock actually support any regex? example: https://hg.adblockplus.org/easylist/rev/c50fec88ffc8

**Comment by gorhill** [comment]
@ryanr: this does the job as far as I can tell:

```
|http://$popup,domain=filenuke.com|sharesix.com
||filenuke.com/a/script.js$script
||sharesix.com/a/script.js$script
```

**Edit:** corrected after d/l'ing latest EasyList

**Comment by ryanbr** [comment]
Our regex for filenuke and sharesix stops the randomly generated scripts from running. Also its easier for filenuke/sharesix to change /a/script.js continuously. Personally I'd prefer to attempt to break popup scripts.

**Comment by gorhill** [comment]
@ryanbr

> Personally I'd prefer to attempt to break popup scripts

Agreed. Looking at it closer, it does look to me the following filter would match the same as the new regexes which were added:

```
||nvy.sharesix.com/*/*$script
```

**Comment by ryanbr** [comment]
The subdomain kept changing, if you see some of the commits for filenuke; https://hg.adblockplus.org/easylist/log?rev=filenuke.com you'll see what I mean

**Comment by gorhill** [comment]
It's an eternal cat and mouse game, they are obviously keeping an eye on EasyList, and will just craft the name of their scripts to go around whatever filter is current -- even if it's a regex. Now it's their turn to counter.
