### ISSUE TITLE
[Firefox] Blocked count Label misaligned

### ISSUE THREAD

**Issue by Schabernack** [uBlock-LLC/uBlock#545]
On current FF and ublock version, the Label showing how many items were blocked on the current page seems to be not positioned correctly:

![screen shot 2015-01-19 at 11 59 33 am](https://cloud.githubusercontent.com/assets/155029/5804304/cfda1e48-9fd2-11e4-8157-f9f5d38928ee.png)

**Comment by ImSpecial** [comment]
Same issue, using the very latest as of now, v0.8.6.0.

![Alt Text](http://i.imgur.com/nr9fRQe.png)

**Comment by shrx** [comment]
Since this is the original issue, the workaround should be mentioned here: go to the Extension's Preferences and disable the option `Show the number of blocked requests on the icon`.

**Comment by muhasturk** [comment]
Seems fixed in Firefox 36.0.x

**Comment by skoftoby** [comment]
Still having this issue on Firefox 36.
![](http://i.imgur.com/SokID38.png)

**Comment by Schabernack** [comment]
36 fixed it for me.

**Comment by gorhill** [comment]
@skoftoby What version of uBlock was this? It has happened to me that an older uBlock was used even after drag-n-dropping a newer version, not sure why. So if this happens again, please report the version of uBlock (from the title bar in the popup).

**Comment by ghost** [comment]
@gorhill The problem is still occuring on µBlock 0.8.8.2 (version according to the add-on list and the popup title bar).

**Comment by ghost** [comment]
Apologies, I forgot to mention I was using a theme that reduced the height of the menu bar dramatically. Reverting to the default theme fixed the issue.

For people using custom CSS or themes that alter the menu bar's dimensions, it would be nice to see an option to center/realign the blocked count label.

**Comment by gorhill** [comment]
> The problem is still occuring on µBlock 0.8.8.2

The issue was fixed in [0.8.9.1](https://github.com/gorhill/uBlock/releases)...
