### ISSUE TITLE
[Chrome] uBlock is blocking Youtube history from being recorded

### ISSUE THREAD

**Issue by NickGeneva** [uBlock-LLC/uBlock#919]
Hello, something that I have come to notice is that uBlock appears to be blocking youtube videos from being recorded into my watch history. I have reset the extension to all defaults and it still seems to be blocking the history update. For the sake of cross referencing I checked ABP and it does not have this issue.

I am using uBlock 0.8.9.1
Anyone else have this issue or is it just me? Thank you!

**Comment by Betsy25** [comment]
Not happening here (uBlock 0.8.9.1 - Firefox nightly - Win7) with out-of-install default 3rd party lists enabled.
Please share your situation.
- Browser + version ?
-  OS ?
- Using by-default checked lists only, no personal rules & filters which could interfere ?

EDIT: Meanwhile, try to see what is getting blocked.
- Have the Youtube History page open, and click the uBlock's popup "eye" icon.
- In "µBlock -- Network request log" tab, click the reload icon on the left, and check which items are getting blocked & by which rule.

**Comment by NickGeneva** [comment]
Hi Betsy, thanks for the reply.
Additional information that was requested:

Browser: Chrome 40.0.2214.115
OS: Win 7
uBlock Settings: Default, 0.8.9.1

To clarify, I believe uBlock is blocking the tracking request that youtube uses to put videos into your history. So if I go watch random video, my history will no be updated. However it works when I shut off uBlock or use a different adblocker extension. I have tested this with other third party extensions on and other third party extensions off and have confirmed that this occurs on three different computers all using chrome.

I checked the requests getting blocked and there's a lot so I am not entirely sure what to look for... would 'youtube.com/ptracking' be involved? Let me know what I need to do and I'll try to get back to you as fast as I can. Thanks for the help.

**Comment by gorhill** [comment]
> use a different adblocker extension

With the **same** filter lists as uBlock?

**Comment by NickGeneva** [comment]
Hi gorhill,
The other ad blocker I used was Ad block plus with Adblock Warning Removal List and Easy List and the allow non-intrusive advertising option off.

**Comment by gorhill** [comment]
It's probably EasyPrivacy then. Digging a bit, here is what I found:

According to this [thread on Adblock Plus' message board](https://adblockplus.org/forum/viewtopic.php?f=2&t=25773&p=109172), the following exception filter was created to un-break Youtube history:

```
@@||s.youtube.com/api/stats/playback?$object-subrequest
```

So I could not see this filter being hit when I try. Turns out it's an exception filter which is suitable for when the Flash player is used. Now Youtube uses the HTML5 player by default, and the closest network request to the one above is blocked:

```
https://s.youtube.com/api/stats/playback?ns=yt&el=detailpag[...]
```

So it appears that with the HTML5 player, the original exception filter needs to be rewritten into:

```
@@||s.youtube.com/api/stats/playback?$image,object-subrequest
```

So try this as custom filter. If this works, then the issue/solution should be reported to EasyPrivacy maintainers: https://forums.lanik.us/viewforum.php?f=64.

**Comment by TteokbokkiNari** [comment]
Had the same issue as OP, and can confirm that @gorhill 's solution works. 

Edit: Made a post, but they have to be approved by the moderator(s) first.

**Comment by NickGeneva** [comment]
Yep, can confirm that its the Easy Privacy filter thanks @gorhill . I cannot seem to register an account on the easy list forums due to some error with their captcha not displaying so thankyou @Daniellynet for posting it. Thanks everyone for the help!

**Comment by TteokbokkiNari** [comment]
> due to some error with their captcha not displaying

Yeah, I had the same issue. Ended up using IE to register instead. 
Still wondering if my post went through, or if they're slow at approving. Cannot seem to find it yet.

**Comment by gorhill** [comment]
I can add an interim fix to EasyPrivacy meanwhile, I will remove when it's fixed on EasyPrivacy side.

**Comment by TteokbokkiNari** [comment]
Update: 
It is fixed now.
https://forums.lanik.us/viewtopic.php?f=64&t=21331&p=67648#p67648

**Comment by robertripoll** [comment]
Still not working for me, I deleted the cache and updated all filters. When I open the Developer Console on Chrome, I'm still getting the net::ERR_BLOCKED_BY_CLIENT message for _s.youtube.com/api/stats_ links.

**Comment by dama-de** [comment]
This makes it work now:

```
@@||s.youtube.com/api/stats/watchtime$image
```
